development:
  app_title: "yGit:Dev"
  repo_path: "repos"
  repo_host: "repos"
  authorized_keys_path: "repos"
  basic_auth_user: "user"
  basic_auth_password: "password1"
  admin_email: "me@example.com"

test:

production:
  app_title: "yGit"
  repo_path: "~/repos"
  repo_host: "user@git.example.com:repos"
  authorized_keys_path: "/home/user_name/.ssh"
  basic_auth_user: "user"
  basic_auth_password: "password1"
  admin_email: "me@example.com"